name: Lint and Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    # Define a matrix to allow for multiple versions if needed in the future
    strategy: 
      matrix:
        node-version: [20.x]

    # Add caching for dependencies to improve performance
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js with the specified version
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 4: Run linting
      - name: Run linter
        run: yarn lint

      # Step 5: Run tests
      # - name: Run tests
      #   run: npm test
